nats_streaming:
  cluster_id: "test-cluster"
  client_id: "test-client"
  channel_name: "test-channel"
  queue_group: "test-group"
  url: "nats://localhost:4222"
http_server:
  address: "localhost: 8080"
  timeout: 4s
  timeout_idle: 60s
database:
  username: "rav"
  password: "Saturn2017!"
  address: "localhost:5432"
  database: "rav"